// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebAPIHospitalCP04.Data;

#nullable disable

namespace WebAPIHospitalCP05.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241010214913_HopsMigration")]
    partial class HopsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIHospitalCP04.Models.PacienteModel", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdPaciente");

                    b.ToTable("PACIENTE");
                });

            modelBuilder.Entity("WebAPIHospitalCP04.Models.PlanoSaudeModel", b =>
                {
                    b.Property<int>("IdPlanoDeSaude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanoDeSaude"));

                    b.Property<string>("Cobertura")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CodPlano")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomePlano")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("PacienteIdPaciente")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdPlanoDeSaude");

                    b.HasIndex("PacienteIdPaciente");

                    b.ToTable("PLANO_DE_SAUDE");
                });

            modelBuilder.Entity("WebAPIHospitalCP04.Models.PlanoSaudeModel", b =>
                {
                    b.HasOne("WebAPIHospitalCP04.Models.PacienteModel", "Paciente")
                        .WithMany("PlanosSaude")
                        .HasForeignKey("PacienteIdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("WebAPIHospitalCP04.Models.PacienteModel", b =>
                {
                    b.Navigation("PlanosSaude");
                });
#pragma warning restore 612, 618
        }
    }
}
